import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import connectMongoDB from "@/lib/DB/MongoConnection";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Tahel-Events | Events Schedule",
	description: "Generated by rm",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// connectMongoDB()
	return (
		<html lang="en" dir="rtl">
			<StoreProvider>
				<body className={inter.className}>
					<Toaster />
					<Theme>{children}</Theme>
				</body>
			</StoreProvider>
		</html>
	);
}
